### ISSUE TITLE
Maven configuration syntax to suppress these types of data races?

### ISSUE THREAD

**Issue by swruch** [vmlens/vmlens#1]
I'm trying to suppress some H2 data races to get my test run to pass, I've tried several variants of the syntax I see in the docs, but I'm not able to suppress them:

0  java.lang.String[]
org.h2.util.StringUtils.cache(java.lang.String) (StringUtils.java:971)
1  java.lang.String[][]
org.h2.util.StringUtils.toUpperEnglish(java.lang.String) (StringUtils.java:87)
2  org.h2.value.ValueInt[]
org.h2.value.ValueInt.get(int) (ValueInt.java:56)

**Comment by ThomasKrieger** [comment]
The following configuration should work:
<suppress>
	<array>java.lang.String[]</array>
	<array>java.lang.String[][]</array>
	<array>org.h2.value.ValueInt[]</array>						 
</suppress>

Have you copied the strings from the html report? I currently use <wbr> for breaking at the "." so it might be that the copied string still contains the wbr and does not work.

**Comment by ThomasKrieger** [comment]
Can you post the part of your pom.xml with the configuration?

**Comment by swruch** [comment]
Thanks for replying.  I had tried the following:

<race>Array@org.h2.util.StringUtils.cache</race>
<race>java.lang.String[]@org.h2.util.StringUtils.cache</race>

I was thinking that suppressing java.lang.String[] or [][] would be overly broad, in case there were issues in my code with String arrays.

**Comment by ThomasKrieger** [comment]
You can use:
```maven
<doNotTrace>
    <method>org.h2.util.StringUtils.cache</method>
    <method>org.h2.util.StringUtils.toUpperEnglish</method>
</doNotTrace>
```
This will tell vmlens to not trace the two methods where the data race happens. 

I think being able to specify the method in the suppress method using @ is a good idea but is currently not implemented.
So I hope the above method works as a workaround

**Comment by ThomasKrieger** [comment]
With version 1.1.0 vmlens now support the @ notation to selectively filter data races. See the example [pom.xml](https://github.com/vmlens/vmlens-examples/blob/master/pom.xml)

You can now write:
```xml
<suppress>
<race>int[]@com.vmlens.examples.config.TestSuppressPrimitiveArrayWithAt.updateArray</race>
<race>java.lang.String[]@com.vmlens.examples.config.TestSuppressArrayWithAtAndPattern.*</race>
</suppress>
```
