### ISSUE TITLE
UnsupportedOperationException when using onlyTraceIn

### ISSUE THREAD

**Issue by gitaroktato** [vmlens/vmlens#5]
When I try to use the Gradle plugin with the `onlyTraceIn` option I get an `UnsupportedOperationException`

## How to reproduce?
Check out the `gradle-plugin-test` branch from [here](https://github.com/gitaroktato/java-concurrency-testing-samples/tree/gradle-plugin-test)

Execute the following command

```bash
./gradlew clean test interleave --stacktrace
```

## Details
I used the [vmlens documentation](https://vmlens.com/help/manual/#the-gradle-plugin-1) to configure Gradle support to my project.

![image](https://user-images.githubusercontent.com/1140629/103274902-1e41a100-49c3-11eb-9db9-51d12293fce8.png)
 
Note, that running `mvn test` is just fine and showing the issues

**Comment by ThomasKrieger** [comment]
Thanks for the bug report. I fixed it with the newest release, version 1.1.5
